name       : python-monotonic
version    : 1.3
release    : 1
source     :
    - https://github.com/atdt/monotonic/archive/1.3.tar.gz : 47fcccc18ee9f3e80c74553eb9b74579fda8b93c504689427042109039f1e4d9
license    : Apache-2.0
component  : programming.python
summary    : An implementation of time.monotonic() for Python
description: |
    This module provides a monotonic() function which returns the value (in fractional seconds) of a clock which never goes backwards.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
install    : |
    %python_install
