name       : python-monotonic
version    : '1.5'
release    : 3
source     :
    - https://files.pythonhosted.org/packages/19/c1/27f722aaaaf98786a1b338b78cf60960d9fe4849825b071f4e300da29589/monotonic-1.5.tar.gz : 23953d55076df038541e648a53676fb24980f7a1be290cdda21300b3bc21dfb0
license    : Apache-2.0
component  : programming.python
summary    : An implementation of time.monotonic() for Python
description: |
    This module provides a monotonic() function which returns the value (in fractional seconds) of a clock which never goes backwards.
builddeps  :
    - python-setuptools
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test
    %python3_test
