name       : python-monotonic
version    : '1.6'
release    : 6
source     :
    - https://pypi.io/packages/source/m/monotonic/monotonic-1.6.tar.gz : 3a55207bcfed53ddd5c5bae174524062935efed17792e9de2ad0205ce9ad63f7
license    : Apache-2.0
component  : programming.python
summary    : An implementation of time.monotonic() for Python
description: |
    This module provides a monotonic() function which returns the value (in fractional seconds) of a clock which never goes backwards.
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
